"""Type stubs for PoetFlow exceptions."""

class PoetFlowError(Exception): ...

class PluginError(PoetFlowError): ...

class MonoRepoError(PoetFlowError): ...

class ConfigError(PoetFlowError): ...

class PackageError(PoetFlowError): ... 