"""Type stubs for monorepo types."""

from typing import Any, Dict, List, Optional, Protocol, Set
from pathlib import Path

from .discovery import PackageInfo

class MonoRepo(Protocol):
    """Protocol for monorepo operations"""
    root_path: Path
    def get_packages(self) -> List[str]: ...
    def get_package_info(self, name: str) -> Optional[Dict[str, Any]]: ...
    def get_package(self, name: str) -> Optional[PackageInfo]: ...
    def get_build_order(self) -> List[str]: ...
    def get_package_path(self, name: str) -> Optional[Path]: ...
    def get_all_packages(self) -> List[str]: ...
    def get_affected_packages(self) -> Set[str]: ...
    def get_all_dependents(self, package: str) -> Set[str]: ...
    def get_dependencies(self, package: str) -> Set[str]: ...
    def execute_command(self, command: str, **kwargs: Any) -> Any: ...

class MonorepoManager(Protocol):
    """Protocol for monorepo manager operations"""
    def get_affected_packages(self) -> Set[str]: ...
