"""Type stubs for Poetry console commands."""
from .poetry import Command

class Application:
    """Poetry console application."""
    def __init__(self) -> None: ...
    def add(self, command: Command) -> None: ...

class AddCommand(Command): ...
class BuildCommand(Command): ...
class EnvCommand(Command): ...
class InstallCommand(Command): ...
class LockCommand(Command): ...
class RemoveCommand(Command): ...
class SelfCommand(EnvCommand): ...
class UpdateCommand(Command): ... 