name: Publicar no PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Permissão necessária para o Trusted Publishing
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Construir pacote
        run: python -m build

      - name: Publicar no PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
